apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: yolo
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
        # autoscaling.knative.dev/target-burst-capacity: "0"
        autoscaling.knative.dev/window: "6s"
    spec:
      nodeSelector:
        kubernetes.io/hostname: node3
      containers:
      - image: docker.io/daohiep22/yolo:latest
        ports:
          - containerPort: 8080
